### ISSUE TITLE
Minimum chunk size

### ISSUE THREAD

**Issue by fhunleth** [cocoa-xu/cvt_color#2]
When OpenMP is enabled, the minimum chunk size can be 0. For example, I naively did this as a quick test:

```elixir
CvtColor.cvt(<< 0,1,2,3,4,5>>, :bgr888, :bgr565)
```

I was about to send a PR to protect against 0 chunk sizes, but I feel like that's not the right fix. It seems like it should be quite a bit larger since there's overhead for multiple cores. And then I figured that powers of 2 chunk sizes would be preferable as well to avoid having all but the first chunk land on a nice memory boundary.

I figured that you might have an intuition as to what would be good size or perhaps what you'd like in the interim.

**Comment by cocoa-xu** [comment]
Hi, thanks for opening the issue! I didn't consider this condition before. 

As a solution, I've added another argument to allow users to explicitly set the minimum chunk size. Because a lot of things can potentially affect the performance, it's really difficult to have an appropriate pre-defined value.

```elixir
min_chunk_size = 65536
bgr565_data = CvtColor.cvt(binary_data, :bgr888, :bgr565, min_chunk_size)
```

In this way, users can benchmark the performance on their devices and choose the value that fits their requirements.

**Comment by cocoa-xu** [comment]
Some benchmark results from the GitHub workflows. It seems that `min_chunk_size` does not affect much on the x86_64 testing machine. I'll try to benchmark it on a Raspberry Pi 4 later.

```
USE_OPENMP=ON
omp_get_max_threads: 2
min_chunk_size: 65536
convert 7680x4320 for 100 times
convert from RGB888 => RGB666Compact: 54.89ms per convert
convert from RGB888 => RGB666: 30.42ms per convert
convert from RGB888 => RGB565: 36.29ms per convert
USE_OPENMP=ON
omp_get_max_threads: 2
min_chunk_size: 262144
convert 7680x4320 for 100 times
convert from RGB888 => RGB666Compact: 54.78ms per convert
convert from RGB888 => RGB666: 30.29ms per convert
convert from RGB888 => RGB565: 36.08ms per convert
USE_OPENMP=ON
omp_get_max_threads: 2
min_chunk_size: 1048576
convert 7680x4320 for 100 times
convert from RGB888 => RGB666Compact: 55.34ms per convert
convert from RGB888 => RGB666: 30.59ms per convert
convert from RGB888 => RGB565: 36ms per convert
USE_OPENMP=ON
omp_get_max_threads: 1
min_chunk_size: 65535
convert 7680x4320 for 100 times
convert from RGB888 => RGB666Compact: 55.52ms per convert
convert from RGB888 => RGB666: 30.06ms per convert
convert from RGB888 => RGB565: 71.74ms per convert
```

**Comment by cocoa-xu** [comment]
So I ran some [benchmarks](https://github.com/cocoa-xu/cvt_color#benchmarks) and it seems that `chunk_size` should be somewhere between 65536 and 1048576 (and should be a power of 2, ofc).
